print('=' * 21)
print('Sobre seu nascimento')
print('=' * 21)
dia = input('\nQual é o dia do seu nascimento? ')
mes = input('Qual é o mês do seu nascimento? ')
ano = input('Qual é o ano do seu nascimento? ')
print('\nVocê nasceu no dia',dia,'de',mes,'de',ano,'. Correto?')
